### ISSUE TITLE
addFetchCondition to get only text/html content type?

### ISSUE THREAD

**Issue by msudol** [simplecrawler/simplecrawler#494]
- *Did you try the latest simplecrawler version from Github? Occasionally there's a lag between the master branch and npm releases. Checking that the problem hasn't already been fixed on Github ensures we don't get duplicate issues.*
No.
- *Do you have a simple test case? It helps a lot if you can boil down your code to a simple test case that we can run to reproduce the problem.*
I want to add a fetch condition to only fetch contentType text/html  and not text/xml, I've tried a fetch condition

    crawler.addFetchCondition((queueItem, referrerQueueItem, callback) => {
       callback(null, queueItem.stateData.contentType == 'text/html');
    });

## What happened?

It fetched the initial page and nothing else at the next depth...  when I remove the fetch condition it fetches all the links properly.

## What should have happened?

Fetch all the links of type text/html

This is probably simple, but the docs are a little tough for me to get complete understanding of how everything works with this package.

**Comment by kbychkov** [comment]
The `stateData` object is empty when accessed in [`addFetchCondition`](https://github.com/simplecrawler/simplecrawler#fetch-conditions) because the resource was not yet requested at that moment and the headers was not received. Thus, you have always negative condition `undefined == 'text/html'` that prevents other resources to get in the queue. Alternatively you could use [`addDownloadCondition`](https://github.com/simplecrawler/simplecrawler#download-conditions) to check `contentType` and skip download.

**Comment by msudol** [comment]
makes sense.... I ended up altering it to queueitem.url and unmatching the .xml extension, works well enough to just get pages.  Thanks!
